export const CRM_SUB_MODULE_MENU: MenuDef[] = [
  {
    name: "Accounts",
    href: "/accounts",
    menuItems: [
      { name: "accounts 1", href: "#" },
      { name: "accounts 2", href: "#" },
      { name: "accounts 3", href: "#" },
      { name: "accounts 4", href: "#" },
      { name: "accounts 5", href: "#" },
      { name: "accounts 6", href: "#" },
    ],
  },
  {
    name: "Contacts",
    href: "/contacts",
    menuItems: [
      { name: "contacts 1", href: "#" },
      { name: "contacts 2", href: "#" },
      { name: "contacts 3", href: "#" },
      { name: "contacts 4", href: "#" },
      { name: "contacts 5", href: "#" },
      { name: "contacts 6", href: "#" },
    ],
  },
  {
    name: "Leads",
    href: "/leads",
    menuItems: [
      { name: "leads 1", href: "#" },
      { name: "leads 2", href: "#" },
      { name: "leads 3", href: "#" },
      { name: "leads 4", href: "#" },
      { name: "leads 5", href: "#" },
      { name: "leads 6", href: "#" },
    ],
  },
  {
    name: "Opportunities",
    href: "/opportunities",
    menuItems: [
      { name: "opportunities 1", href: "#" },
      { name: "opportunities 2", href: "#" },
      { name: "opportunities 3", href: "#" },
      { name: "opportunities 4", href: "#" },
      { name: "opportunities 5", href: "#" },
      { name: "opportunities 6", href: "#" },
    ],
  },
  {
    name: "Tasks",
    href: "/tasks",
    menuItems: [
      { name: "tasks 1", href: "#" },
      { name: "tasks 2", href: "#" },
      { name: "tasks 3", href: "#" },
      { name: "tasks 4", href: "#" },
      { name: "tasks 5", href: "#" },
      { name: "tasks 6", href: "#" },
    ],
  },
  {
    name: "Calendar",
    href: "/calendar",
    menuItems: [
      { name: "calendar 1", href: "#" },
      { name: "calendar 2", href: "#" },
      { name: "calendar 3", href: "#" },
      { name: "calendar 4", href: "#" },
      { name: "calendar 5", href: "#" },
      { name: "calendar 6", href: "#" },
    ],
  },
  {
    name: "Dashboard",
    href: "/dashboard",
    menuItems: [
      { name: "dashboard 1", href: "#" },
      { name: "dashboard 2", href: "#" },
      { name: "dashboard 3", href: "#" },
      { name: "dashboard 4", href: "#" },
      { name: "dashboard 5", href: "#" },
      { name: "dashboard 6", href: "#" },
    ],
  },
];
